title: 617VIP
desc: Wicked Silly News
email: fromweru@gmail.com # provisional
address: "Call: 617-383-7232 <br>Write: 617VIP, Inc.<br> Address: 867 Boylston Street, 5th Floor Boston, MA 02116"
description: 'Wicked Silly News'
baseurl: "/617vip"
url: "http://617vip.com" 
copyright: Copyright 617VIP, Inc. All Rights Reserved
twitter_username: the617vip
markdown: kramdown
theme: minima
paginate: 6
paginate_path: '/page:num/'
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude: ['Gemfile', 'Gemfile.lock']
defaults:
  -
    scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
permalink: /:title/