title: 617VIP
desc: Wicked Silly News
email: your-email@domain.com
address: "Call: 617-383-7232 <br>Write: 617VIP, Inc.<br> Address: 867 Boylston Street, 5th Floor Boston, MA 02116"
description: 'Wicked Silly News'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://617vip.com" 
copyright: Copyright 617VIP, Inc. All Rights Reserved
twitter_username: the617vip
markdown: kramdown
theme: minima
paginate: 6
paginate_path: '/page:num/'
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
