title: 617VIP
email: your-email@domain.com
address: "Call <br> 617-383-7232 <br>Write: 617VIP, Inc.<br> 867 Boylston Street, 5th Floor Boston,<br> MA 02116"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
copyright: Copyright 617VIP, Inc. All Rights Reserved
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
